# Generated by Django 4.2.11 on 2024-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('discription', models.TextField()),
                ('category', models.CharField(choices=[('sa', 'Sculpture'), ('ph', 'Photography'), ('ar', 'Art'), ('pa', 'Painting')], max_length=2)),
                ('art_image', models.ImageField(upload_to='art')),
            ],
        ),
    ]
