# Generated by Django 4.2.11 on 2024-04-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='book',
            new_name='art',
        ),
    ]
